---
- name: Disable Swap
  become: yes
  command: swapoff --all
  ignore_errors: yes

- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Copy Kubernetes Repo File
  become: yes
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Install Kubernetes
  become: yes
  yum: 
    name: "{{ item }}"
    state: installed
  with_items:
  - docker
  - kubelet 
  - kubectl
  - kubeadm

- name: Ensure Docker Group
  become: yes
  group:
    name: docker
    state: present

- name: Ensure User in Docker Group
  become: yes
  user:
    name=vagrant
    groups=docker
    append=yes

- name: Copy k8s.conf
  become: yes
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Create .kube directory
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: 0700

- name: Enable and Start Kubelet
  become: yes
  service:
    name: "kubelet"
    enabled: yes
    state: started

- name: Enable and Start Docker
  become: yes
  service:
    name: "docker"
    enabled: yes
    state: started

- name: Pass bridged IPv4 traffic to iptables
  become: yes
  shell: >
    sysctl net.bridge.bridge-nf-call-iptables=1

- name: Pass bridged IPv6 traffic to iptables
  become: yes
  shell: >
    sysctl net.bridge.bridge-nf-call-ip6tables=1

- name: Refresh Kernel Settings
  become: yes
  shell: >
    sysctl --system

- name: Disable SELinux
  become: yes
  shell: >
    setenforce 0
