---
- hosts: nfs-server
  vars:
    nfs_export_ip: "192.168.2.0/24"
  roles:
  - common
  - nfs-server

- hosts: kube-masters 
  vars:
    kube_token: "e6aedd.1ffbc1ff421d950d" 
    kube_advertise: "192.168.2.21"
    nfs_server_ip: "kube-nfs"
    overlay: "flannel"
  roles:
  - common
  - nfs-client
  - docker
  - kube-base
  - kube-master
  - flannel 
  - weave 

- hosts: kube-nodes
  vars:
    kube_token: "e6aedd.1ffbc1ff421d950d" 
    kube_advertise: "192.168.2.21"
    nfs_server_ip: "kube-nfs"
  roles:
  - common
  - nfs-client
  - docker
  - kube-base
  - kube-node
