---
- name: Run kubeadm init
  become: yes
  command: kubeadm join --token={{ kube_token }} {{ kube_advertise }}:6443 --discovery-token-unsafe-skip-ca-verification
  args:
    creates: /etc/.kubeadmjoin

- name: Block kubeadm init
  become: yes
  command: touch /etc/.kubeadmjoin
