---
- name: Run kubeadm init
  become: yes
  command: kubeadm init --token={{ kube_token }} --pod-network-cidr={{ kube_network }}
  args:
    creates: /etc/.kubeadminit

- name: Block kubeadm init
  become: yes
  command: touch /etc/.kubeadminit

- name: Copy Kubeconfig To Mount
  become: yes
  command: cp /etc/kubernetes/admin.conf /mnt/nfsfileshare

- name: Copy Kubeconfig To Home
  become: yes
  command: cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config

- name: Setup Config Permissions
  become: yes
  file:
    path: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Apply Flannel Overlay
  command: kubectl apply -f {{ flannel_url }}
  args:
    creates: /etc/.flannel

- name: Block flannel
  become: yes
  command: touch /etc/.flannel
